version: '3'

services:
  beast:
    build: ./beast
    ports:
      - "8080:8080"

  react:
    build: ./react
    ports:
      - "5174:5174"
    depends_on:
      - express

  express:
    build: ./express
    ports:
      - "5000:5000"
    depends_on:
      - beast

